src/training/tesstrain.sh usr/share/tesseract-ocr/
src/training/language-specific.sh usr/share/tesseract-ocr/
src/training/tesstrain_utils.sh usr/share/tesseract-ocr/
debian/tesstrain /usr/bin/
/usr/bin/ambiguous_words
/usr/bin/classifier_tester
/usr/bin/cntraining
/usr/bin/combine_lang_model
/usr/bin/combine_tessdata
/usr/bin/dawg2wordlist
/usr/bin/lstmeval
/usr/bin/lstmtraining
/usr/bin/merge_unicharsets
/usr/bin/mftraining
/usr/bin/set_unicharset_properties
/usr/bin/shapeclustering
/usr/bin/text2image
/usr/bin/unicharset_extractor
/usr/bin/wordlist2dawg
/usr/share/man/man1/ambiguous_words.*
/usr/share/man/man1/classifier_tester.*
/usr/share/man/man1/cntraining.*
/usr/share/man/man1/combine_lang_model.*
/usr/share/man/man1/combine_tessdata.*
/usr/share/man/man1/dawg2wordlist.*
/usr/share/man/man1/lstmeval.*
/usr/share/man/man1/lstmtraining.*
/usr/share/man/man1/merge_unicharsets.*
/usr/share/man/man1/mftraining.*
/usr/share/man/man1/set_unicharset_properties.*
/usr/share/man/man1/shapeclustering.*
/usr/share/man/man1/text2image.*
/usr/share/man/man1/unicharset_extractor.*
/usr/share/man/man1/wordlist2dawg.*
/usr/share/man/man5*
